Update zh_cn.lang
mezz/JustEnoughItems pull request #1073
Opened 2017-12-15 12:56 UTC by Snownee

2017-12-15 12:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1073) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1073) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=1073) it.</sub>

2017-12-16 04:06 UTC, mezz commented
Thank you!
@3TUSK can you review this?

2017-12-16 04:15 UTC, liach commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +jei.tooltip.error.recipe.transfer.too.large.player.inventory=配方不是 2×2 的
最好表示此配方在2*2的格子里面装不下

2017-12-16 04:25 UTC, Snownee commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +jei.tooltip.error.recipe.transfer.too.large.player.inventory=配方不是 2×2 的
然而原文如此，建议你先让原文改过来

2017-12-16 05:00 UTC, liach commented
@mezz https://github.com/mezz/JustEnoughItems/blob/1.12/src/main/resources/assets/jei/lang/en_us.lang#L20
I suggest you directly pointing out that the recipe is too large in this entry.

2017-12-16 05:08 UTC, mezz commented
The original English localization for that is bad, I agree. I will think of something better.

2017-12-16 05:38 UTC, liach commented
Thanks!

2017-12-16 06:40 UTC, 3TUSK requested changes

2017-12-16 06:40 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +# DEBUG (for debug mode, do not need translation)
117 - 120 行可以直接删掉了

2017-12-16 06:40 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +config.jei.search.modNameSearchMode=@模组名称
105 - 116 行位置不对，什么情况？

2017-12-16 07:24 UTC, Snownee commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +config.jei.search.modNameSearchMode=@模组名称
脚本问题，具体原因不得而知

2017-12-16 08:19 UTC, Snownee commented
@3TUSK 
手动整理了一下

2017-12-16 08:21 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> -# DEBUG （调试用条目，不需翻译，请不要将英文条目重新复制回来）
还是建议把这几行按原来的方式留空...

2017-12-17 06:46 UTC, 3TUSK approved these changes

2017-12-17 17:06 UTC, liach approved these changes

2017-12-17 22:52 UTC, merged