Fix #1202 by changing enchanments to ingredients
mezz/JustEnoughItems pull request #1402
Opened 2018-11-19 15:47 UTC by naqaden

Thanks to @HenryLoenwind for the [suggestion](https://github.com/mezz/JustEnoughItems/issues/1202#issuecomment-410721993).

2018-11-19 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=1402) it.</sub>

2018-11-23 03:54 UTC, mezz requested changes
Thanks for contributing!
This looks good but there are a couple small things to fix before I can merge it.
1. We will need a way to bridge the gap with recipes that use enchanted books right now. I have something hacked into recipe lookups for items that hold fluids, we can add another case to support old recipes that use enchanted books there. See `mezz.jei.recipes.RecipeRegistry#getRecipeWrappers` for the fluidstack special case handling.
2. JEI's existing enchanted book anvil recipes need to be updated

2018-11-23 03:54 UTC, mezz commented on src/main/java/mezz/jei/plugins/vanilla/ingredients/EnchantDataRenderer.java
> +public class EnchantDataRenderer implements IIngredientRenderer<EnchantmentData> {
You should pass in an instance of `IIngredientRenderer<ItemStack>` to the constructor of this renderer, and use it to render the enchanted books.

2018-11-29 23:39 UTC, naqaden commented
Thanks for that guidance. I don't yet see where to update anvil recipes, so right now each enchanted book shows anvil recipes for all enchanted books.

There's also a small issue where the previously blank enchanted book on the JEI items screen now renders with Protection I on it.

2018-12-08 23:54 UTC, mezz commented
I am working on adding oredict as an ingredient as well.
I think this PR will be a bit easier after that change is in, could take a while longer to get everything working right though.

2018-12-09 09:38 UTC, HenryLoenwind commented
oredict may be a bit trickier, as there are instances were we'd have lists of oredicts and itemstacks. Would a way to lookup all ingredients' recipes of a cycling slot at once be better? (This may need a way for teh recipe to tell you if it is cycling ingredient alternatives or recipe variants.)

2018-12-09 19:25 UTC, mezz commented
I've thought a lot about that question, and I was thinking oredict is the right way forward because of tags in 1.13.
With tags, it's even easier to create small groups of items for recipes.

That said, I'm not really convinced it's the right way either. I have implemented it in a branch so I can play around with it and see what corner cases I run into. So far there are a few pretty big ones where mods don't use oredict but still have large lists of items.

I am going to break off some pieces of my oredict branch that might benefit this PR. 
After that I will try the other approach, which is improving the way cycled ingredients are displayed and  navigated.

2018-12-09 20:41 UTC, mezz commented
This PR is pretty close to done, so I will update it and merge it in.

2018-12-10 04:01 UTC, mezz commented
I ended up changing this pretty dramatically.
Now the "enchant" ingredient is pretty much hidden from mods and the players, it will just act like the regular enchanted books.
I tested it in a few packs and situations where mods are added or removed, and it seems to work as intended now.

2018-12-10 04:04 UTC, merged