Update zh_cn.lang for next version
mezz/JustEnoughItems pull request #1447
Opened 2019-01-02 01:20 UTC by mcBegins2Snow

2019-01-02 01:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1447) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=1447) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=1447) it.</sub>

2019-01-02 03:52 UTC, mezz commented
Thank you!

@3TUSK can you review?

2019-01-02 04:43 UTC, 3TUSK requested changes
I was summoned.

2019-01-02 04:43 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +jei.tooltip.error.recipe.transfer.too.large.player.inventory=配方不是 2x2 的
Revert this. That `×` is `U+00D7, &#215; MULTIPLICATION SIGN`.

2019-01-02 04:43 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +config.jei.interface.bookmarkOverlayEnabled.comment=在打开的 GUI 旁边显示书签列表。
Either change this one (as following), or change the above one (`在打开的 GUI 一侧显示物品列表` -> `在打开的 GUI 旁边显示物品列表`).
```suggestion
config.jei.interface.bookmarkOverlayEnabled.comment=在打开的 GUI 一侧显示书签列表。
```

2019-01-02 04:43 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +jei.tooltip.bookmarks.usage.key=将鼠标悬停在某个成分上，然后按“%s”将其添加为书签。
No quotation marks.
```suggestion
jei.tooltip.bookmarks.usage.key=将鼠标悬停在某个成分上，然后按 %s 将其添加为书签。
```

2019-01-02 04:43 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +jei.tooltip.bookmarks.usage.nokey=在“按键”设置中为 JEI 书签添加按键设置。
![image](https://user-images.githubusercontent.com/9113033/50580595-2d59dc80-0e05-11e9-9f6d-84bfe20550c6.png)
```suggestion
jei.tooltip.bookmarks.usage.nokey=在按键设置中为 JEI 书签添加快捷键。
```

or

```suggestion
jei.tooltip.bookmarks.usage.nokey=在“控制…”中为 JEI 书签添加按键设置。
```

I prefer the first one.

2019-01-02 04:43 UTC, 3TUSK commented on src/main/resources/assets/jei/lang/zh_cn.lang
> +key.jei.toggleBookmarkOverlay=显示/隐藏加入书签的成分
除了“成分”还能怎么翻译？“成分”听上去很奇怪。

2019-01-02 08:45 UTC, mcBegins2Snow commented
The translation improvement was completed.

2019-01-04 06:17 UTC, 3TUSK approved these changes

2019-01-06 04:03 UTC, mezz commented
Thank you both!

2019-01-06 04:04 UTC, merged