WIP Port to 1.17
mezz/JustEnoughItems pull request #2426
Opened 2021-07-24 22:28 UTC by pupnewfster

2021-07-24 22:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=2426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=2426) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pupnewfster<br/>:x: shartte<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=2426) it.</sub>

2021-08-03 03:36 UTC, mezz requested changes

2021-08-03 03:36 UTC, mezz commented on src/api/java/mezz/jei/api/constants/VanillaRecipeCategoryUid.java
> +	 * Automatically includes every {@link SmeltingRecipe}
should this be `CampfireCookingRecipe`?

2021-08-03 03:36 UTC, mezz commented on src/main/java/mezz/jei/plugins/vanilla/ingredients/item/ItemStackListFactory.java
> +		//TODO: Test to make sure this is actually fixed in 1.17 and if so remove this check
good todo 👍

2021-08-03 03:39 UTC, pupnewfster commented on src/api/java/mezz/jei/api/constants/VanillaRecipeCategoryUid.java
> +	 * Automatically includes every {@link SmeltingRecipe}
Yes, I misread the line when I was changing it and thought it was some generic abstract/anonymous implementation mojang was using so didn't rename it.

2021-08-03 03:42 UTC, mezz approved these changes

2021-08-03 03:43 UTC, merged