fix log spam of "Could not find a matching ingredient to remove ..." every time recipes are reloaded
mezz/JustEnoughItems pull request #2954
Opened 2022-08-16 04:27 UTC by Goldenlion5648

changed the spam to only happen on debug mode

2022-08-16 04:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=2954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=2954) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=2954) it.</sub>

2022-08-18 02:01 UTC, mezz commented
Thanks for contributing!
Could you just make this a debug-level log instead?

2022-08-18 03:48 UTC, Goldenlion5648 commented
Done.

2022-08-18 05:35 UTC, mezz commented
Ah sorry I wasn't very clear, I mean it doesn't even need to be locked behind `if(clientConfig.isDebugModeEnabled())` if it's just a debug log.
Can you just make it a 1-word change from `error` to `debug`? Thanks again :D

2022-08-18 05:36 UTC, mezz commented
Actually I have an idea, I can edit it on github, one sec.

2022-08-18 05:37 UTC, mezz requested changes

2022-08-18 05:37 UTC, mezz commented on Forge/src/main/java/mezz/jei/ingredients/IngredientManager.java
> +					if(clientConfig.isDebugModeEnabled()) {
```suggestion
					if (LOGGER.isDebugEnabled()) {
```

2022-08-18 05:39 UTC, mezz approved these changes

2022-08-18 05:39 UTC, merged