[API] Add methods to add & remove smelting and anvil recipes during runtime
mezz/JustEnoughItems pull request #819
Opened 2017-04-17 23:12 UTC by Mohron

2017-04-17 23:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=819) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mezz/JustEnoughItems?pullRequest=819) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mezz/JustEnoughItems?pullRequest=819) it.</sub>

2017-04-18 00:52 UTC, Mohron commented
> mezz> Mohron, how are you going about removing existing smelting and anvil recipes that are added by JEI internally?

I actually don't know. Will that even be possible?

2017-04-18 23:19 UTC, mezz commented
You can get the recipe wrapper by creating a focus and looking it up with `IRecipeRegistry`. Is that good enough? I'm not sure there's a better way to do it.

2017-04-18 23:39 UTC, mezz requested changes

2017-04-18 23:39 UTC, mezz commented on src/main/java/mezz/jei/recipes/RecipeRegistry.java
> +		Preconditions.checkNotNull(output, "null output");
There is `ErrorUtil.checkNotEmpty` for `ItemStack`, please use it here.

2017-04-18 23:39 UTC, mezz commented on src/main/java/mezz/jei/recipes/RecipeRegistry.java
> +		addRecipe(smeltingRecipe);
This method should not add recipe, it should be a separate step.

2017-04-18 23:39 UTC, mezz commented on src/main/java/mezz/jei/recipes/RecipeRegistry.java
> +		addRecipe(Collections.singletonList(anvilRecipeWrapper), VanillaRecipeCategoryUid.ANVIL);
This method should not add the recipe, it should be a separate step.

2017-04-18 23:39 UTC, mezz commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * Add a new anvil recipe while the game is running.
Should be "Create a new anvil recipe."

2017-04-18 23:39 UTC, mezz commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * Add a new smelting recipe while the game is running.
Should be "Create a new smelting recipe."

2017-04-18 23:44 UTC, Mohron commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * By default, all smelting recipes from {@link FurnaceRecipes#smeltingList} are already added by JEI.
@mezz do you want this line to stay?

2017-04-18 23:46 UTC, mezz commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * By default, all smelting recipes from {@link FurnaceRecipes#smeltingList} are already added by JEI.
Yep

2017-04-18 23:48 UTC, Mohron commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * Add a new smelting recipe while the game is running.
Should I add:
`Use {@link #addRecipe(IRecipeWrapper, String)} to add the recipe while the game is running.`
To each method's Doc tags as well?

2017-04-18 23:49 UTC, mezz commented on src/api/java/mezz/jei/api/IRecipeRegistry.java
> +	 * Add a new smelting recipe while the game is running.
That's good, yeah.

2017-04-18 23:54 UTC, mezz requested changes

2017-04-18 23:54 UTC, mezz commented on src/main/java/mezz/jei/recipes/RecipeRegistry.java
> +		Preconditions.checkNotNull(output);
There is `ErrorUtil.checkNotEmpty` for `ItemStack`, please use it here.

2017-04-18 23:57 UTC, mezz commented
Looks good, there is still one thing left to fix.

2017-04-18 23:58 UTC, Mohron commented
Ya I missed the part where i was using something completely different (from the old API method) so I just removed the string param.

2017-04-19 00:11 UTC, mezz approved these changes

2017-04-19 00:11 UTC, merged